source "https://api.berkshelf.com"

metadata

cookbook 'apt', '~> 2.6.1'
cookbook 'runit', '~> 1.5.14'
cookbook 'ohai', '~> 2.0.1'
cookbook 'build-essential', '~> 2.1.3'

cookbook 'java', '~> 1.29.0'
cookbook 'monit', '~> 0.7.5'

cookbook 'nginx', '~> 2.7.4'
cookbook 'elasticsearch', '~> 0.3.13'