name             'search'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures search'
long_description 'Installs/Configures search'
version          '0.1.0'

depends 'apt'
depends 'java'
depends 'monit'
depends 'elasticsearch'